### ISSUE TITLE
Feature Request: Androw for React Native Modal

### ISSUE THREAD

**Issue by WrathChaos** [folofse/androw#12]
Hello @folofse,
I tried Androw on [ React-Native-Modal](https://github.com/react-native-community/react-native-modal)) however, it does not work on Modal component. Do you have any idea how to implement it on Modal?

**Comment by folofse** [comment]
Hi @WrathChaos, 
I will install the React-Native-Modal in the example and see if I can figure out why it's not working.

**Comment by folofse** [comment]
Im able to use Androw inside a Modal like the following, it renders a shadow around the white square. You can also remove the modal background by adding a custom backdrop

`<View style={{ flex: 1 }}>
				<Button title="Show modal" onPress={this.toggleModal} />
				
				<Modal 	isVisible={this.state.isModalVisible} 
						customBackdrop={<View style={{ flex: 1, opacity:0 }} />}>
					<Androw style={{shadowOpacity: .5,
									shadowRadius: 5,
									shadowColor: '#ff00ff',
									shadowOffset: {
										width: 0,
										height: 0,
									},
								}}>
						<View style={{ width:100, height: 100, backgroundColor:'white' }}>
							<Text>Hello!</Text>
							<Button title="Hide modal" onPress={this.toggleModal} />
						</View>
					</Androw>
				</Modal>
			</View>`
