### ISSUE TITLE
Components wrapped with Androw doesnt rerender on old Android

### ISSUE THREAD

**Issue by Solistratos** [folofse/androw#13]
Hi. There's an issue with updating components view. On android 9 everything's fine. I have not tested on 8, but on android 7 component wrapped with Androw becomes static, it updates it's view only once.

 ````typescript
const Component:FC = () => {
 const [buttonName, setButtonName] = useState('Button')

 useEffect(()=> {
 setTimeout(() => {
   setButtonName('Definitely not button')
  }, 1000)
 })

 return <Androw><Button>{name}</Button></Androw>
}
````
In that example code the button's name will always remain 'Button'.

**Comment by folofse** [comment]
@Solistratos, Yes, it seems like the rerender not triggers in Android 7.0. I will look in to this and see if I can find any solution.

**Comment by thilek** [comment]
in RNAndrowLayout.java inside `dispatchDraw(Canvas canvas)`, remove the `else`  and moving `super.dispatchDraw(canvas);` outside fixed the issue. In this case `super.dispatchDraw(canvas);` always been called.

**Comment by rferdosi** [comment]
Still not working in android 5.

**Comment by folofse** [comment]
@rferdosi You won't be able to submit an app below API level 28 to Google play Store, so I have not focused on older devices.

https://developer.android.com/distribute/best-practices/develop/target-sdk
