### ISSUE TITLE
Androw not working only for Text Component

### ISSUE THREAD

**Issue by WrathChaos** [folofse/androw#16]
Hello @folofse,
I've tried to set shadow for Android with Androw on Text component however it simply does not work and throw an error.  Do you think is that possible to use Androw for Text component as well?  (I'm gonna upload the error image ASAP)

Reproducible code: 
```

import { Text } from "react-native"
import Androw from "react-native-androw"

 <Androw
    style={{
          shadowOpacity: 0.7,
          shadowColor: "#000",
          shadowOffset: {
            width: 0,
            height: 2
          }
    }}
>
    <Text
       style={{
            fontSize: 18,
            marginRight: 16,
            color: "#fdfdfd",
            textAlign: "right"
       }}
    >
       {`${someValues}`}
    </Text>
</Androw>
```

**Comment by folofse** [comment]
Hi @WrathChaos  

Unfortunately I´m not able to recreate your problem, could you please provide the error screen and I will investigate it further.

**Comment by WrathChaos** [comment]
I think it was my wrong usage. Closed it. Thank you @folofse
