### ISSUE TITLE
TouchableOpacity not working 

### ISSUE THREAD

**Issue by ydv0121** [folofse/androw#3]
hello,

i want to set shadow at the bottom of the header only, but can't able to set
i am using Native-Base's header component
please see attachment what i exactly want

<img width="218" alt="Screenshot 2019-05-08 at 2 58 03 PM" src="https://user-images.githubusercontent.com/37238045/57365033-efe5d100-71a1-11e9-8695-3a7b619be56a.png">

**Comment by ydv0121** [comment]
is there any solution?

**Comment by folofse** [comment]
I made a simple test and it worked, so I'm not sure what problem you experiencing.

`import React, { Component } from 'react';
import {StyleSheet} from 'react-native';
import { Container, Header, Left, Body, Right, Button, Icon, Title } from 'native-base';

import Androw from 'react-native-androw';

export default class App extends Component {
	render() {
		return (
			<Container>
				<Androw style={styles.shadow}>
					<Header>
						<Left>
							<Button transparent>
								<Icon name='arrow-back' />
							</Button>
						</Left>
						<Body>
							<Title>Header</Title>
						</Body>
						<Right>
							<Button transparent>
								<Icon name='menu' />
							</Button>
						</Right>
					</Header>
				</Androw>
			</Container>
		);
	}
}
const styles = StyleSheet.create({

	shadow: {
		shadowColor: '#0000ff',
		shadowOpacity: .3,
		shadowRadius: 20,
		shadowOffset: {
			width: 0,
			height: 20,
		}
	}
});`

**Comment by ydv0121** [comment]
yes it's worked..
actually i used header as a componet that's why i had some problem..
it's worked

**Comment by ydv0121** [comment]
can you please check TouchableOpacity is not working inside <Header> when we use <Androw>
here is my piece of code

`   <Androw style={Platform.OS == 'android'?styles.shadowHeader:{zIndex:1}}>
      <Header
          style={styles.header}
          androidStatusBarColor="#eeeeee"
        backgroundColor={theme.white} >
          <TouchableOpacity style={{justifyContent:'center',top:2}} onPress={() => Actions.pop()}>
              <Icon name="md-arrow-back" style={styles.hederBackButton}/>
          </TouchableOpacity>
          <View style={styles.headerTitle}>
            <Title>
              <Text style={styles.headerTitleText}>Login</Text>
            </Title>
          </View>
          <Right></Right>
        </Header>
        </Androw>`

**Comment by ydv0121** [comment]
it's worked need to assign more width to <TouchableOpacity>
