### ISSUE TITLE
about New Version

### ISSUE THREAD

**Issue by ydv0121** [folofse/androw#5]
hello
i upgrade the module on new version you changes yerterday
it's totally diffrent then the previous..it's totally misbehave in old shadow styles..
the TouchableOpacity working properly superb...but can't adjust shadow
i think quality of shadow also not so good like 0.0.20 version
so how to use new version?

**Comment by folofse** [comment]
I have tweaked the shadows to be work as the shadows does in iOS and in CSS like https://www.cssmatic.com/box-shadow this means that a shadow with shadowOffset width and height 0 and a radius with 5 gets 5 around the whole component and not just on one side. This means that the shadows size increases with 5 on each side and a total size of componentSize + 5 + 5. This makes it possible to also use the shadow as a glow effect

**Comment by ydv0121** [comment]
Can you please provide example of that?

**Comment by ydv0121** [comment]
is there any example available?
