### ISSUE TITLE
is shadow position works different as per android version??

### ISSUE THREAD

**Issue by ydv0121** [folofse/androw#7]
i have implement shadow and run the project but it will show diffrent position as per android version like in android 9.0(pie) it's perfect..
but below android 9(pie) like android 7(nougat) android 8(oreo).. it's diffrent from same code

is there issue or it will actually work like that???

here is my example and screenshot:

`<Androw style={Platform.OS == 'android'?styles.shadow:null}>
<View style={{height:100,width:100,backgroundColor:'grey',justifyContent:'center',alignItems:'center'}}>
<TouchableOpacity onPress={()=>alert('ok')}>
        <Image
        style={{height:50,width: 50}}
        source={{
            uri: 'http://pngimg.com/uploads/google/google_PNG19645.png',
        }}
    /></TouchableOpacity>
        </View>
        </Androw>
`

### Android 9(Pie)

![Screenshot_20190610-100742_shadow](https://user-images.githubusercontent.com/37238045/59172859-db617380-8b67-11e9-8e9e-57376945e020.png)

### Android 8(Oreo)

 
![Screenshot_20190610-100629](https://user-images.githubusercontent.com/37238045/59172973-65a9d780-8b68-11e9-8560-906a965d7aa3.jpg)

**Comment by ydv0121** [comment]
one more thing i notice is that shadowOpacity not affecting ..if i change to 0.4 to 1 OR 1 to 0.4 it will same

**Comment by folofse** [comment]
New version available. Fixed positions and opacity.

**Comment by ydv0121** [comment]
yes checked out..it's working properly..
thank you @folofse for listening on issues and provide new update very shortly
thank you buddy ...it's perfect package
let's spread shadow.

#HappyShadow
