### ISSUE TITLE
annotation issue

### ISSUE THREAD

**Issue by ydv0121** [folofse/androw#8]
how to resolve this..getting this since morning in my react native project after i added 
android.useAndroidX=true
android.enableJetifier=true
 

 to my gradle.properties

![Screenshot 2019-06-18 at 11 03 31 AM](https://user-images.githubusercontent.com/37238045/59655746-f875f200-91b8-11e9-9338-3d1d9e44545b.png)

**Comment by folofse** [comment]
Make sure you have this in dependencies in your android project /app/build.gradle
`implementation "com.android.support:appcompat-v7:28.0.0"`

Or if you use androidX you can change the import to `import androidx.annotation.NonNull;` instead.

**Comment by ydv0121** [comment]
> Make sure you have this in dependencies in your android project /app/build.gradle
> `implementation 'com.android.support:support-annotations:28.0.0'`
> 
> Or if you use androidX you can change the import to `import androidx.annotation.NonNull;` instead.

yes i am using com.android.support:support-annotations:28.0.0 ..
and where to change import import androidx.annotation.NonNull;???

**Comment by ydv0121** [comment]
actually after updated play-service in reacet-native run-android i am getting this error..that's why i put this 
android.useAndroidX=true
android.enableJetifier=true



![Screenshot 2019-06-18 at 10 25 32 AM](https://user-images.githubusercontent.com/37238045/59657558-b18afb00-91be-11e9-8053-3d11cbb47af5.png)

**Comment by folofse** [comment]
Ok, I see

You can test to replace 
`import android.support.annotation.NonNull;`
with
`import androidx.annotation.NonNull;`

**Comment by ydv0121** [comment]
ok thank you error is gone in react-native-androw
but got many errors from other library after add this in gadle.properties 
android.useAndroidX=true
android.enableJetifier=true

do you know how to remove androidx from my entire react native project

> actually after updated play-service in reacet-native run-android i am getting this error..that's why i put this
> android.useAndroidX=true
> android.enableJetifier=true
> 
> ![Screenshot 2019-06-18 at 10 25 32 AM](https://user-images.githubusercontent.com/37238045/59657558-b18afb00-91be-11e9-8053-3d11cbb47af5.png)

**Comment by folofse** [comment]
I believe you can remove these
```
android.useAndroidX=true
android.enableJetifier=true
```
Or set them to false

```
android.useAndroidX=false
android.enableJetifier=false
```

**Comment by ydv0121** [comment]
> android.useAndroidX=false
> android.enableJetifier=false

ohk let me try..what about this ->
 tools:replace="android:appComponentFactory" terminal show this to add this in in mainfest

**Comment by folofse** [comment]
I'm not sure, but after you have removed the useAndroidX you can try to run "refactor>migrate app to app compat" in Android Studio

**Comment by ydv0121** [comment]
> I'm not sure, but after you have removed the useAndroidX you can try to run "refactor>migrate app to app compat" in Android Studio

is it cause anything else?

**Comment by folofse** [comment]
I think it just changes all imports from androidx to android app compat..

**Comment by ydv0121** [comment]
ohk let me try..i removed this **import androidx.annotation.NonNull;** form react-native androw
