### ISSUE TITLE
app crash when use androw in long list like chat

### ISSUE THREAD

**Issue by ydv0121** [folofse/androw#9]
hello brother @folofse ,
i getting crashes in my app when use androw in long list like chat or something else which contain so many data in list..
i am getting this error from last 20 days..finally figured out it's beacuse of androw called in flatlist..

when i look this error very carefully i read that 
**UpdateRecursive**
 **UIImplementation.java**

after wasted so many hours/days find that it's beacuse of androw **when i comment all androw tag no crashes occur so far**

i think it might be because of last update when render **recalled for image rendering.**

here is screenshot from debug and from android studio

![Screenshot_1561111891](https://user-images.githubusercontent.com/37238045/59916718-911ca400-943d-11e9-9ee8-2d43f871de3b.png)

![Screenshot 2019-06-21 at 2 27 25 PM](https://user-images.githubusercontent.com/37238045/59917542-d9d55c80-943f-11e9-963d-d6738a83c501.png)

is it fixable?? or androw is not usable in listview/flatlists?

**Comment by ydv0121** [comment]
@folofse am i right about this error???

**Comment by folofse** [comment]
I will test this and report back to you..

**Comment by ydv0121** [comment]
ohh yes..i am not aware of virtual list..let me try with virtual list..Thank you

**Comment by folofse** [comment]
I got the same error with multiple androw items, I will investigate to see If I can solve this problem . You will get the best performance from the app by wrapping the whole list in one androw list, this way the view will only re-render once its needed.

```
import React, { Component } from 'react';
import {
	FlatList,
	StyleSheet,
	Text,
	View,
} from 'react-native';

import Androw from 'react-native-androw';

export default class App extends Component {

	render() {
		const list = Array.from(new Array(1000)).map((obj, idx)=>{return {key:'id'+idx, value:"Item number "+idx}});

		return (
			<View style={styles.container}>

				<View style={{ width: '100%' }}>
					<FlatList
						containerStyle={{width:'100%', height:'100%', backgroundColor:'lightGrey'}}
						data={list}
						renderItem={({item}) => <Androw style={{
							shadowOpacity: .5,
							shadowRadius: 10,
							shadowColor: '#ff00ff',
							shadowOffset: {
								width: 0,
								height: 0,
							}
						}}>
							<Text style={{width:'100%', }} key={item.key}>{item.value}</Text>
						</Androw>}

					/>
				</View>
			</View>
		);
	}
}
const styles = StyleSheet.create({
	container: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#F5FCFF',
	},
	welcome: {
		fontSize: 20,
		textAlign: 'center',
		margin: 10,
	},
	instructions: {
		textAlign: 'center',
		color: '#333333',
		marginBottom: 5,
	},
	androw: {
		justifyContent: 'center',
		alignItems: 'flex-start',
	},

});
```

**Comment by folofse** [comment]
I got the same error so I will investigate to see if I can resolve this problem. If your able you can wrap the whole list in one androw, this will give the app the best performance.

```
import React, { Component } from 'react';
import {
	Image,
	FlatList,
	StyleSheet,
	Text,
	View,
} from 'react-native';

import Androw from 'react-native-androw';

export default class App extends Component {

	getURI() {
		const rand = Math.floor(Math.random() * 999);
		//const uri = "https://picsum.photos/2000/2000?random=" + rand;
		const uri = "https://picsum.photos/2000/2000";
		console.log(uri);
		return uri;
	}

	render() {
		const list = Array.from(new Array(50)).map((obj, idx) => { return { key: 'id' + idx, value: "Item number " + idx } });
		console.log(list);
		return (
			<View style={styles.container}>

				<View style={{ width: '100%' }}>


					<Androw style={{
						width: '100%',
						height: '100%',
						shadowOpacity: .5,
						shadowRadius: 10,
						shadowColor: '#ff00ff',
						shadowOffset: {
							width: 0,
							height: 0,
						}
					}}>
						<FlatList
							containerStyle={{ width: '100%', height: '100%', backgroundColor: 'lightGrey' }}
							data={list}
							renderItem={({ item }) => <Text style={{ width: '100%', }} key={item.key}>{item.value}</Text>}
						/>
					</Androw>

				</View>
			</View>
		);
	}
}
const styles = StyleSheet.create({
	container: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		backgroundColor: '#F5FCFF',
	},
	welcome: {
		fontSize: 20,
		textAlign: 'center',
		margin: 10,
	},
	instructions: {
		textAlign: 'center',
		color: '#333333',
		marginBottom: 5,
	},
	androw: {
		justifyContent: 'center',
		alignItems: 'flex-start',
	},

});
```

**Comment by ydv0121** [comment]
I have a chat module..i applied androw to the dynamic message text view...so when my all messages came from DB...crashes happen..if i got 10-20 messages ..androw will apply in every messsages

**Comment by ydv0121** [comment]
like this i applied shadow

![Screenshot 2019-06-24 at 4 35 49 PM](https://user-images.githubusercontent.com/37238045/60014249-29b15f00-969e-11e9-8086-7b06c8dab345.png)

**Comment by ydv0121** [comment]
@folofse is it fixable?

**Comment by ydv0121** [comment]
app is crashing in long list view..is it able to fix??

**Comment by folofse** [comment]
Sorry for late feedback, I have now manage to solve this crash bug in version 0.0.33, keep in mind that this version uses androidX.

**Comment by lake2** [comment]
app crashs or becomes stuck when using androw in section list item.
